# Generated by Django 2.2.10 on 2020-03-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Image',
                'verbose_name': 'Image',
            },
        ),
    ]
