# Generated by Django 2.2.10 on 2020-03-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockermanage', '0002_asset_imagetmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpamPoolModel',
            fields=[
                ('subnet', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('iprange', models.CharField(max_length=72)),
                ('gateway', models.CharField(max_length=100)),
                ('aux_addresses', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'IpamPool',
                'verbose_name': 'IpamPool',
            },
        ),
    ]
