# Generated by Django 3.0.3 on 2020-03-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockermanage', '0004_auto_20200309_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumesMode',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('driver', models.CharField(max_length=100)),
                ('driver_opts', models.CharField(max_length=200)),
                ('labels', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Volumes',
                'verbose_name_plural': 'Volumes',
            },
        ),
    ]
