# Generated by Django 3.0.3 on 2020-03-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dockermanage', '0007_auto_20200316_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configmodel',
            name='lable',
        ),
    ]
